src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Enum\CategoriesType;
use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category_name = null;

    /**
     * @var Collection<int, Products>
     */
    #[ORM\OneToMany(targetEntity: Products::class, mappedBy: 'category')]
    private Collection $products;

    // 👇 Changed this part
    #[ORM\Column(type: 'string', length: 50, enumType: CategoriesType::class)]
    private ?CategoriesType $type = null;

    /**
     * @var Collection<int, Services>
     */
    #[ORM\OneToMany(targetEntity: Services::class, mappedBy: 'category')]
    private Collection $services;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): static
    {
        $this->category_name = $category_name;
        return $this;
    }

    /**
     * @return Collection<int, Products>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): static
    {
        if ($this->products->removeElement($product)) {
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    // 👇 Enum getter/setter
    public function getType(): ?CategoriesType
    {
        return $this->type;
    }

    public function setType(?CategoriesType $type): static
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return Collection<int, Services>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Services $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
            $service->setCategory($this);
        }

        return $this;
    }

    public function removeService(Services $service): static
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getCategory() === $this) {
                $service->setCategory(null);
            }
        }

        return $this;
    }
    
}

src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Enum\ServicesType;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
class Services
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'services')]
    private ?Categories $category = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(enumType: ServicesType::class)]
    private ?ServicesType $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?ServicesType
    {
        return $this->status;
    }

    public function setStatus(ServicesType $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ServicesType.php
<?php

namespace App\Form;

use App\Entity\Services;
use App\Entity\Categories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Enum\ServicesType as EnumServicesType;
use Doctrine\ORM\EntityRepository;

class ServicesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('category', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'category_name',
                'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('c')
                            ->where('c.type = :type')
                            ->setParameter('type', 'service');
                    },
                    'placeholder' => 'Select Service Category',
                ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'Active' => EnumServicesType::Active,
                    'Inactive' => EnumServicesType::Inactive,
                ],
                'expanded' => false,
                'multiple' => false,
                'label' => 'Service Status',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Services::class,
        ]);
    }
}

src/Controller/ServicesController.php
<?php

namespace App\Controller;

use App\Entity\Services;
use App\Form\ServicesType;
use App\Repository\ServicesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/services')]
final class ServicesController extends AbstractController
{
    #[Route(name: 'app_services_index', methods: ['GET'])]
    public function index(ServicesRepository $servicesRepository): Response
    {
        return $this->render('services/index.html.twig', [
            'services' => $servicesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_services_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $service = new Services();
        $form = $this->createForm(ServicesType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($service);
            $entityManager->flush();

            return $this->redirectToRoute('app_services_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('services/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_services_show', methods: ['GET'])]
    public function show(Services $service): Response
    {
        return $this->render('services/show.html.twig', [
            'service' => $service,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_services_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Services $service, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ServicesType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_services_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('services/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_services_delete', methods: ['POST'])]
    public function delete(Request $request, Services $service, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($service);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_services_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/services/_delete_form.html.twig
<form method="post" action="{{ path('app_services_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="px-5 py-2 bg-red-600 text-white rounded-lg shadow hover:bg-red-800 cursor-pointer" data-turbo="false">
        🗑 Delete
    </button>
</form>

templates/services/_form.html.twig
{{ form_start(form, {'attr': {'class': 'space-y-6'}}) }}

    <div>
        {{ form_label(form.name, 'Service Name', {'label_attr': {'class': 'block text-sm font-medium text-gray-900'}}) }}
        {{ form_widget(form.name, {'attr': {'class': 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-black'}}) }}
        {{ form_errors(form.name) }}
    </div>

    <div>
        {{ form_label(form.description, 'Description', {'label_attr': {'class': 'block text-sm font-medium text-gray-900'}}) }}
        {{ form_widget(form.description, {'attr': {'class': 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-black'}}) }}
        {{ form_errors(form.description) }}
    </div>

    <div>
    {{ form_label(form.category, 'Category', {'label_attr': {'class': 'block text-sm font-medium text-gray-900'}}) }}
    {{ form_widget(form.category, {'attr': {'class': 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-black'}}) }}
    {{ form_errors(form.category) }}
</div>

    <div>
        {{ form_label(form.price, 'Price', {'label_attr': {'class': 'block text-sm font-medium text-gray-900'}}) }}
        {{ form_widget(form.price, {'attr': {'class': 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-black'}}) }}
        {{ form_errors(form.price) }}
    </div>

    <div>
        {{ form_label(form.status, 'Status', {'label_attr': {'class': 'block text-sm font-medium text-gray-900'}}) }}
        {{ form_widget(form.status, {'attr': {'class': 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 text-black'}}) }}
        {{ form_errors(form.status) }}
    </div>

    <div class="pt-4">
        <button data-turbo="false" type="submit" class="w-full px-6 py-2 bg-green-600 text-white rounded-lg shadow hover:bg-green-700 cursor-pointer">
            ✅ Save Product
        </button>
    </div>

{{ form_end(form) }}

templates/services/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Services{% endblock %}

{% block body %}
    {% include 'admin/sidebar.html.twig' %}

    <div class="flex-1 flex flex-col overflow-hidden">

        {% include 'admin/header.html.twig' %}

        <div class="flex justify-center p-8 mb-10">
            <div class="w-full max-w-2xl bg-white p-8 rounded-xl shadow-lg">
                <h1 class="text-3xl font-bold mb-6  text-gray-800 text-center">Edit Service</h1>

                <div class="bg-gray-50 p-6 rounded-lg shadow-md">
                    {{ include('services/_form.html.twig', {'button_label': 'Update'}) }}
                </div>

                <div class="mt-6 flex justify-center space-x-8">
                    <a href="{{ path('app_services_index') }}" data-turbo="false"
                    class="px-4 py-2 bg-gray-500 text-white rounded-lg shadow hover:bg-gray-600">
                        ⬅ Back to list
                    </a>

                    {{ include('services/_delete_form.html.twig') }}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/services/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Services index{% endblock %}

{% block body %}
    {% include 'admin/sidebar.html.twig' %}

<div class="flex-1 flex flex-col overflow-hidden">
    {% include 'admin/header.html.twig' %}

    <div class="flex justify-center p-4">
        <div class="w-full max-w-7xl bg-white p-8 rounded-xl shadow-lg">
            <h1 class="text-2xl font-bold mb-4 text-gray-800 text-center">Services Index</h1>

            <div class="overflow-x-auto bg-gray-100 p-3 rounded-lg shadow-md">
                <table id="servicesTable" class="w-full border-collapse border border-gray-300 bg-white rounded-lg overflow-hidden shadow">
                    <thead class="bg-gray-100 text-gray-700">
                        <tr>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Id</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Name</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Description</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Category</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Price</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-left">Status</th>
                            <th class="border border-gray-300 px-2 py-2 text-sm font-semibold text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="servicesTableBody" class="divide-y divide-gray-200">
                        {% for service in services %}
                            <tr class="odd:bg-white even:bg-gray-50 hover:bg-gray-100">
                                <td class="border border-gray-300 px-2 py-1 text-center">{{ service.id }}</td>
                                <td class="border border-gray-300 px-2 py-1 font-medium text-gray-900">{{ service.name }}</td>
                                <td class="border border-gray-300 px-4 py-2 text-gray-700">{{ service.description }}</td>
                                <td class="border border-gray-300 px-2 py-1 font-medium text-gray-900">
                                    {{ service.category ? service.category.categoryName : 'No category' }}
                                </td>
                                <td class="border border-gray-300 px-2 py-1 text-gray-700 text-center">₱{{ service.price }}</td>
                                <td class="border border-gray-300 px-2 py-1 text-gray-700 text-center">{{ service.status.value|capitalize }}</td>
                                <td class="border border-gray-300 px-2 py-1 text-center">
                                    <a href="{{ path('app_services_show', {'id': service.id}) }}" 
                                       class="text-blue-600 hover:text-blue-800 font-semibold">Show</a> <br/>
                                    <a href="{{ path('app_services_edit', {'id': service.id}) }}" 
                                       class="text-yellow-600 hover:text-yellow-800 font-semibold">Edit</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="7" class="px-4 py-2 text-center text-gray-500 bg-gray-50">
                                    No records found
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="mt-6 text-center">
                <a href="{{ path('app_services_new') }}" 
                   class="inline-block px-5 py-2 bg-green-600 text-white rounded-lg shadow hover:bg-green-700">
                    + Create new
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/services/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Services{% endblock %}

{% block body %}
    {% include 'admin/sidebar.html.twig' %}

<div class="flex-1 flex flex-col overflow-hidden">

    {% include 'admin/header.html.twig' %}

    <div class="flex justify-center p-8 mb-10">
        <div class="w-full max-w-2xl bg-white p-8 rounded-xl shadow-lg">
            <h1 class="text-3xl font-bold mb-6  text-gray-800 text-center">Add New Service</h1>

            <div class="bg-gray-50 p-6 rounded-lg shadow-md">
                {{ include('services/_form.html.twig') }}
            </div>

            <!-- Action Buttons -->
            <div class="mt-6 flex justify-center">
                <a href="{{ path('app_services_index') }}" data-turbo="false"
                class="px-5 py-2 bg-gray-500 text-white rounded-lg shadow hover:bg-gray-600">
                    ⬅ Back to list
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/services/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Services{% endblock %}

{% block body %}
{% include 'admin/sidebar.html.twig' %}

<div class="flex-1 flex flex-col overflow-hidden">

    {% include 'admin/header.html.twig' %}

    <div class="flex justify-center p-8 mb-10">
        <div class="w-full max-w-3xl bg-white p-8 rounded-xl shadow-lg">
            <h1 class="text-3xl font-bold text-gray-800 text-center">service Details</h1>

            <div class="overflow-hidden rounded-lg shadow-md bg-gray-50 p-6">
                <table class="table-auto w-full mx-auto border border-gray-300 rounded-lg mb-8">
                    <tbody>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">ID</th>
                            <td class="px-4 py-3 border border-gray-300">{{ service.id }}</td>
                        </tr>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">Name</th>
                            <td class="px-4 py-3 border border-gray-300">{{ service.name }}</td>
                        </tr>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">Description</th>
                            <td class="px-4 py-3 border border-gray-300 whitespace-normal break-words max-w-lg">
                                {{ service.description }}
                            </td>
                        </tr>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">Category</th>
                            <td class="px-4 py-3 border border-gray-300">{{ service.category ? service.category.categoryName : 'No category' }}</td>
                        </tr>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">Price</th>
                            <td class="px-4 py-3 border border-gray-300">₱{{ service.price }}</td>
                        </tr>
                        <tr>
                            <th class="w-40 border border-gray-300 px-4 py-3 text-left bg-gray-100 font-semibold">status</th>
                            <td class="px-4 py-3 border border-gray-300">{{ service.status.value|capitalize }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Action Buttons -->
            <div class="mt-6 flex justify-center space-x-4 ">
                <a href="{{ path('app_services_index') }}" data-turbo="false" class="px-5 py-2 bg-gray-500 text-white rounded-lg shadow hover:bg-gray-600">
                    ⬅ Back to list
                </a>

                <a href="{{ path('app_services_edit', {'id': service.id}) }}" class="px-5 py-2 bg-blue-600 text-white rounded-lg shadow hover:bg-blue-700">
                    ✏ Edit
                </a>

                {{ include('services/_delete_form.html.twig') }}
            </div>
        </div>
    </div>

</div>
{% endblock %}